### ISSUE TITLE
futureRollbackSQL shows Unexpected argument(s): ***

### ISSUE THREAD

**Issue by gutiram** [liquibase/liquibase-github-action#13]
I'm trying to run a futureRollbackSQL but seems to be that is not working. I'm ataching my yml file and a pic with the output.
The error shows: Unexpected argument(s): ***

`
name: LiquibaseFutureRollbackSQL
on: workflow_dispatch

jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v3
        with:
          operation: 'futureRollbackSQL'
          classpath: 'db-migrations'
          changeLogFile: 'changelog-db.mssql.sql'
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          url: ${{ secrets.URL }}
`
![image](https://user-images.githubusercontent.com/77328278/138516123-00289985-0cf2-438d-9c29-88203dd7c690.png)

**Comment by jnewton03** [comment]
Hi @gutiram , thanks for using Liquibase! We're about to publicly announce our brand new github actions that support all Liquibase commands, command parameters, and global parameters. Take a look!
https://github.com/liquibase-github-actions
