### ISSUE TITLE
Need tagExists --tag <tag string> command

### ISSUE THREAD

**Issue by krisha-vumc** [liquibase/liquibase-github-action#14]
Hi,
I am creating a pipeline for rollback with on dispatch_workflow where the tag is passed as an input. Before running liquibase rollback operation I want to run tagExists operation so that we can catch error as early as possible. Thank you.

**Comment by awhitford-cip** [comment]
What happens if you rollback to a non-existent tag?  (Presumable it fails, no?)

**Comment by jnewton03** [comment]
Hi @krisha-vumc , thanks for using Liquibase! We're about to publicly announce our brand new github actions that support all Liquibase commands, command parameters, and global parameters. Take a look!
https://github.com/liquibase-github-actions
