### ISSUE TITLE
Support for Labels

### ISSUE THREAD

**Issue by sashadorval** [liquibase/liquibase-github-action#18]
I use labels on my changesets to build for different environments, a command including labels might look something like:
`liquibase --changeLogFile changelog.json --labels v1 update`.

I wasn't able to find documentation for providing labels to the github action, just wondering if it exists but is not documented, or if it could be included as a feature?

Thank you for this github action, very appreciative that it exists at all!

**Comment by jnewton03** [comment]
Hi @sashadorval , thanks for using Liquibase! We're about to publicly announce our brand new github actions that support all Liquibase commands, command parameters, and global parameters. Take a look!
https://github.com/liquibase-github-actions
