### ISSUE TITLE
Support for liquibaseSchemaName

### ISSUE THREAD

**Issue by KirioXX** [liquibase/liquibase-github-action#26]
We have our liquibase changelog in a custom schema and specify this schema in a `liquibase.properties` file.
Is it possible to either use the config in the properties file or to set the schema in the action to make it accessible for the action?

Thanks

**Comment by jnewton03** [comment]
Hi @KirioXX , thanks for using Liquibase! We're about to publicly announce our brand new github actions that support all Liquibase commands, command parameters, and global parameters. Take a look!
https://github.com/liquibase-github-actions
