### ISSUE TITLE
Support db-doc

### ISSUE THREAD

**Issue by awhitford-cip** [liquibase/liquibase-github-action#29]
Please support the [db-doc](https://docs.liquibase.com/commands/docs/db-doc.html) command.

**Comment by jnewton03** [comment]
hi @awhitford-cip , thanks for using Liquibase!  We're about to publicly announce our brand new github actions that support all Liquibase commands, command parameters, and global parameters.  Take a look!
https://github.com/liquibase-github-actions/db-doc
