### ISSUE TITLE
Passing runtime parameters?

### ISSUE THREAD

**Issue by menzenski** [liquibase/liquibase-github-action#30]
Is there a way to pass runtime parameters to this github action?

Currently I have a github action that writes to an ephemeral `liquibase.properties` file with per-job parameters. This requires an additional job step before the liquibase action is called:

```yaml
      - name: Prepare liquibase.properties file
        run: |
          touch liquibase.properties
          echo parameter.etl_user_name=${{ secrets.ETL_USER_NAME }} > liquibase.properties
          echo parameter.etl_user_password=${{ secrets.ETL_USER_PASSWORD }} > liquibase.properties
```

Is there a way to just pass these parameters as runtime parameters instead?

I would love to be able to use `-Detl_user_name=${{ secrets.ETL_USER_NAME }} -Detl_user_password=${{ secrets.ETL_USER_PASSWORD }}` instead of writing to a file in an extra step.

**Comment by szandany** [comment]
Passing the `-Dkey=value`​ pair can be done outside of the command using the `JAVA_OPTS`​ environment variable.

In the workflow, under your **env**​ section, you can include the environment variable, `JAVA_OPTS` and assign the appropriate values for the properties you would like to set. 

Let's say you have the variables "**DAY**" and "**MONTH**" and you would like to assign those to the following values from your secrets:
```
secrets.DAY
secrets.MONTH
```
You can pass those as part of the `JAVA_OPTS` "`-D`" arguments.
Script example:
```bash
env:
  JAVA_OPTS: "-DDAY=${{ secrets.DAY }} -DMONTH=${{ secrets.MONTH }}"
```

**Comment by jnewton03** [comment]
Hi @menzenski, thanks for using Liquibase! We're about to publicly announce our brand new github actions that support all Liquibase commands, command parameters, and global parameters. Take a look!
https://github.com/liquibase-github-actions
