### ISSUE TITLE
How to use flag?

### ISSUE THREAD

**Issue by krisha-vumc** [liquibase/liquibase-github-action#32]
I am trying to use --log-level flag. Is there a way we can set that up?

**Comment by StevenMassaro** [comment]
You should be able to follow these steps here: https://github.com/liquibase/liquibase-github-action/issues/30#issuecomment-1112536708

**Comment by jnewton03** [comment]
Hi @krisha-vumc , thanks for using Liquibase! We're about to publicly announce our brand new github actions that support all Liquibase commands, command parameters, and global parameters. Take a look!
https://github.com/liquibase-github-actions
