### ISSUE TITLE
Allow specifying of liquibase docker version

### ISSUE THREAD

**Issue by jnewton03** [liquibase/liquibase-github-action#34]
Currently `:latest` is always used:
https://github.com/liquibase/liquibase-github-action/blob/93a18ea3aa903e6e05213dcba43e1578d8b60679/Dockerfile#L1

We should default to `:latest` but allow overriding with a specific docker image tag

**Comment by mcred** [comment]
There is also the potential issue that someone would specific a liquibase version that's not compatible with action.yml spec.

**Comment by gopisaba** [comment]
My current pipeline is broken because on Friday Liquibase released v4.12.0 which has breaking change for snowflake. This is the problem with using latest always.

**Comment by nvoxland** [comment]
@gopisaba :

There was a gap in time where "latest" took the snowflake extension out and before before we upgraded to 4.12.0 which includes the snowflake support directly.

But currently "latest" should work with snowflake just fine. We are looking to improve the docker image management, including ensuring that "latest" builds only come from complete releases. But is the image currently in latest still an issue for you?

**Comment by gopisaba** [comment]
We are using liquibase github actions and it is using the latest docker image always. The pipeline got broken when liquibase bumped the version to 4.12.0.

```
Unexpected error running Liquibase: SQL compilation error:
parse error line 8 at position 44 near '<EOF>'.
syntax error line 6 at position 0 unexpected 'if'. [Failed SQL: (1003) CREATE
OR REPLACE PROCEDURE SCHEMA.PROCNAME(
    SCENARIO_NAME VARCHAR(6),
    SCENARIO_YEAR VARCHAR(4)
) RETURNS STRING LANGUAGE JAVASCRIPT EXECUTE AS CALLER AS '
if(!["El1", "El21"]
    .includes(SCENARIO_NAME)){
        throw "Invalid SCENARIO_NAME Error!"]
```

The above changeset works perfectly well in 4.10.0 but broken in 4.12.0. I thinks it is good idea to pin the version and if someone wants to upgrade they have test it before upgrading especially when the new version has some BREAKING CHANGE in it.

**Comment by nvoxland** [comment]
@gopisaba Are you able to give your complete failing changeset? The error listed is saying the SQL itself is invalid and it seems like it should just be the SQL you  had passed us along. But perhaps there is something else going on in there, like changelog parameters or something else?

**Comment by gopisaba** [comment]
This is the stored procedure that works perfectly well in v4.11.0
```sql
CREATE
OR REPLACE PROCEDURE SCHEMA.PROCNAME(
    SCENARIO_NAME VARCHAR(6),
    SCENARIO_YEAR VARCHAR(4)
) RETURNS STRING LANGUAGE JAVASCRIPT EXECUTE AS CALLER AS '
if(!["El1", "El21"]
    .includes(SCENARIO_NAME)){
        throw "Invalid SCENARIO_NAME Error!"
    }

if(!SCENARIO_YEAR.startsWith("20") || !(SCENARIO_YEAR.length==4)){
    throw "Invalid SCENARIO_YEAR Error!"
}

var JOB_NAME = "Job Name 1";
var SUMMARY = "Summary of the Job";

# AND REST OF THE STORED PROC
```
but in v4.12.0, the liquibase update fails 

```sql
Starting Liquibase at 10:26:21 (version 4.12.0 #3073 built at 2022-06-17 05:59+0000)
Liquibase Version: 4.12.0
Liquibase Community 4.12.0 by Liquibase
Running Changeset: update/proj1/changelogs/changelog-dml.xml::ID-001::Auth
Unexpected error running Liquibase: SQL compilation error:
parse error line 8 at position 44 near '<EOF>'.
syntax error line 6 at position 0 unexpected 'if'. [Failed SQL: (1003) CREATE
OR REPLACE PROCEDURE SCHEMA.PROCNAME(
    SCENARIO_NAME VARCHAR(6),
    SCENARIO_YEAR VARCHAR(4)
) RETURNS STRING LANGUAGE JAVASCRIPT EXECUTE AS CALLER AS '
if(!["El1", "El21"]
    .includes(SCENARIO_NAME)){
        throw "Invalid SCENARIO_NAME Error!"]
For more information, please use the --log-level flag
```
Changeset for the above stored procedure
```xml
    <changeSet id="ID-001" author="Auth" runOnChange="true" >
        <comment>Stored procedure to move data from X to Y layer</comment>
        <sqlFile path="update/proj1/procedures/001_CREATE.sql"/>
    </changeSet>
```

**Comment by gopisaba** [comment]
Thanks for [fixing the issue](https://github.com/liquibase/liquibase/issues/3024) with liquibase. Since it is broken, I ended up writing my own github actions to pin the version to v4.11.0. It would be nice to give the option to pin the version in this actions.

**Comment by jnewton03** [comment]
Hi @gopisaba , thanks for using Liquibase! We're about to publicly announce our brand new github actions that support all Liquibase commands, command parameters, and global parameters. That includes pinning the version of liquibase starting with 4.17!  Take a look!
https://github.com/liquibase-github-actions
