### ISSUE TITLE
Applying for GitHub publisher verification for Liquibase GitHub Action

### ISSUE THREAD

**Issue by kevin-atx** [liquibase/liquibase-github-action#37]
I’m writing regarding the GH Action [Liquibase Github Action](https://github.com/marketplace/actions/liquibase-github-action)

Our project is starting to migrate the CI/CD to GH Actions and we are interested to use your Actions.
Providing some context, our Security team requires the "Creator Verified by GitHub" badge to start the internal GHA verification process, due to this we are blocked to use unverified Actions.

We would be grateful if you could start the GH Action verification process, as it would help us greatly.

I believe it must improve your impact in the whole GitHub community as a partner organization and also, you are letting us use your actions.

You can find more helpful information in the following articles from GitHub Docs as a good starting point on the process.

[Applying for publisher verification for your organization](https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization)
[About marketplace badges](https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/about-marketplace-badges)

**Comment by kevin-atx** [comment]
Alberto - the team was able to look at this quickly and just submitted our organization for verification. I'll keep this ticket open until we hear back. Thanks again for pointing this out.

-Kevin

**Comment by kenta2097** [comment]
> We got our organization verified, and we ended up needing to join the ISV program to get our GitHub action listed as verified. We applied two days ago and are awaiting the response. Once that is complete, the GitHub Action should show as verified as well.
> 
> -Kevin

Hi Kevin, 

There's any update about the process?

Regards,
Alberto M.

**Comment by jnewton03** [comment]
@kevin-atx @kenta2097, thanks for using Liquibase!  We're about to publicly announce our brand new github actions that support all Liquibase commands, command parameters, and global parameters.  These are also Verified by GitHub! Take a look!  
https://github.com/liquibase-github-actions

**Comment by kenta2097** [comment]
@jnewton03 
The plan is to deprecate [Liquibase Github Action](https://github.com/marketplace/actions/liquibase-github-action) on behalf on all these new Actions?

**Comment by jnewton03** [comment]
hi @kenta2097 Sorry for the delay.  Yes, we will eventually deprecate the old action.
