### ISSUE TITLE
Add support for hub.liquibase.com arguments

### ISSUE THREAD

**Issue by nvoxland** [liquibase/liquibase-github-action#4]
To send hub data for update/rollback/etc. operations ran through the github action, we need the following parameters added:

- hubConnectionId
- hubApiKey

Usually the hubApiKey should be passed as a secret, but the action needs a parameter for it.

**Comment by jnewton03** [comment]
Hi @nvoxland , the new github actions should satisfy this ask:
https://github.com/liquibase-github-actions/update/blob/main/action.yml

LMK if so and we can close this issue.  Thanks!
