### ISSUE TITLE
This action connector does not support default schema

### ISSUE THREAD

**Issue by mdpete4** [liquibase/liquibase-github-action#40]
In my environment we are not using the public schema and are using an alternate custom schema instead. Could this action be extended to support the default schema portion of the liquibase command?

**Comment by jnewton03** [comment]
Hi @mdpete4 , thanks for using Liquibase!  We're about to publicly announce our brand new github actions that support all Liquibase commands, command parameters, and global parameters.  Take a look!
https://github.com/liquibase-github-actions

**Comment by jnewton03** [comment]
leaving open in case you have more questions :)
