### ISSUE TITLE
How does liquibase-github-action relate to liquibase-github-actions?

### ISSUE THREAD

**Issue by awhitford-cip** [liquibase/liquibase-github-action#43]
How does [liquibase-github-action](https://github.com/liquibase/liquibase-github-action) relate to [liquibase-github-actions](https://github.com/liquibase-github-actions)?  (What should people use?)

**Comment by StevenMassaro** [comment]
[liquibase-github-actions](https://github.com/liquibase-github-actions) is the "new" incarnation of using Liquibase through GitHub actions. This repository will continue to exist, but likely won't be updated. [liquibase-github-actions](https://github.com/liquibase-github-actions) is programmatically generated so it will be updated as each new version of Liquibase is released. If possible, you may want to switch to [liquibase-github-actions](https://github.com/liquibase-github-actions).

**Comment by awhitford-cip** [comment]
Happy to switch to new [liquibase-github-actions](https://github.com/liquibase-github-actions) approach.  One concern that I have is that it is unclear where the _Issues_ are for those actions.

**Comment by mcred** [comment]
@awhitford-cip Each new action has a section saying where to report issues. Example for update: https://github.com/liquibase-github-actions/update#feedback-and-issues

**Comment by awhitford-cip** [comment]
Perfect!  Sorry I didn't see that.
