### ISSUE TITLE
rolllback or updateTestingRollback does not seem to work

### ISSUE THREAD

**Issue by awhitford-cip** [liquibase/liquibase-github-action#44]
I noticed that _recently_ some bad _rollbacks_ were sneaking into our code base and passing our CI tests that use Liquibase.
In a nutshell, we test Liquibase scripts by applying changes, rolling back those changes, then applying them again.  If that succeeds, chances are that people have valid rollbacks defined.

Alas, here is a simple example that is now passing:
```sql
-- liquibase formatted sql

-- changeset awhitford:create-simple-table
create table AW_SIMPLE (
  SIMPLE_ID int not null comment 'Simple Identifier',
  SIMPLE_DATE date not null comment 'Simple Date'
)
-- rollback drop table AW_DOES_NOT_EXIST_SHOULD_FAIL
```

I can see that the changeset is being applied, but I do not see any evidence that it is being rolled back and reapplied.

I have tried using two approaches:
1. Manual 4-step operations
   1. Tag Database
   2. Update
   3. Rollback (to Tag)
   4. Update
2. New `updateTestingRollback` operation (which does the same thing but in one operation)

I feel like this may have been broken for a few months now, but I can't be certain.  In the 4 step approach, my observation is that it appears that the first two steps work, but the rollback does nothing, and then the subsequent update does nothing.

⚠️ It appears that I am not the only one suffering from this:
* https://forum.liquibase.org/t/liquibase-rollback-acts-like-it-works-but-does-nothing/6132 🐛

**Comment by awhitford-cip** [comment]
Since I migrated to the [liquibase-github-actions](https://github.com/liquibase-github-actions), I cross posted here: liquibase/github-action-generator#59

**Comment by jnewton03** [comment]
@awhitford-cip Thanks!  Since this action is no longer under development I will close this issue.  We are tracking your bug in your cross posted issue.
