### ISSUE TITLE
Missing support for context parameter

### ISSUE THREAD

**Issue by andreasvh-conceto** [liquibase/liquibase-github-action#47]
Hi,

currently the github action does not support contexts parameter. In order to prepare prod or qa databases this feature can be useful. Implementation is done in the following pull request.

https://github.com/liquibase/liquibase-github-action/pull/46

Kind regards
Andreas

**Comment by jnewton03** [comment]
Hi @andreasvh-conceto !  Thanks for using the Liquibase Github Action!  We are no longer doing active development on this action and instead have actions for each liquibase command.  You can read about it here:
https://www.liquibase.com/blog/announcing-the-new-release-of-liquibase-github-actions

The new github org with all of the actions are here:
https://github.com/liquibase-github-actions

These actions should support all command line and global parameters as well.  Thanks for using Liquibase!
