### ISSUE TITLE
docker-entrypoint.sh file does not exist

### ISSUE THREAD

**Issue by m-petuhov** [liquibase/liquibase-github-action#6]
This error appears in github actions:
/entry.sh: line 122: docker-entrypoint.sh: command not found

**Comment by fedorena** [comment]
I have faced the same issue.

**Comment by smcveigh941** [comment]
Same issue here!

**Comment by brianhv** [comment]
I was having the same problem. It looks like #7 fixed this, but the release hasn't been made. To handle this, I changed

```yaml
      uses: liquibase/liquibase-github-action@v1
```

to

```yaml
      uses: liquibase/liquibase-github-action@5231f40
```

This pins the action to the most recent commit as of this comment's writing. Once v1 is updated (or perhaps v2 is released) you'll probably want to change that back.

**Comment by l-j** [comment]
@m-petuhov, @fedorena, @smcveigh941, @brianhv 
A new version of github-action has been released and now it works like a charm with: ```liquibase/liquibase-github-action@v2```
I believe this issue can be closed.

**Comment by jnewton03** [comment]
Resolved by https://github.com/liquibase/liquibase-github-action/pull/7
